### ISSUE TITLE
[Sprint 3] UI Polishing // Search view

### ISSUE THREAD

**Issue by sophiafeng** [imagejourney/imagejourney#19]
Update search view with Material UI
Maybe show preview image in the search results?

**Comment by jamesman11** [comment]
![screen shot 2017-05-12 at 12 59 16 am](https://cloud.githubusercontent.com/assets/6962853/25988825/60898342-36ae-11e7-8d00-925cdf9d28b2.png)
I've gone ahead and make some change, so you can focus on the journal view. I'll close it now.
